#!/bin/bash

source ./config.inc
source ./function.inc

msg_line "Mounting kernel virtual filesystems: "
mount_kernel_vfs
msg_success

chroot "$LFS" $TOOLS/bin/env -i          \
    HOME=/root                         \
    TERM="$TERM"                       \
    PS1='(leoware tools chroot) \u:\w\$ '        \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:$TOOLS/bin \
    $TOOLS/bin/bash --login +h

msg_line "Unmounting kernel virtual filesystems: "
umount_kernel_vfs
msg_success
